// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.repay.wallet.domain;

import com.repay.wallet.domain.TxnType;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TxnType_Roo_Configurable {
    
    declare @type: TxnType: @Configurable;
    
}
