// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.repay.wallet.domain;

import com.repay.wallet.domain.Txn;
import com.repay.wallet.domain.TxnDataOnDemand;
import com.repay.wallet.domain.TxnIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TxnIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TxnIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TxnIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TxnIntegrationTest: @Transactional;
    
    @Autowired
    TxnDataOnDemand TxnIntegrationTest.dod;
    
    @Test
    public void TxnIntegrationTest.testCountTxns() {
        Assert.assertNotNull("Data on demand for 'Txn' failed to initialize correctly", dod.getRandomTxn());
        long count = Txn.countTxns();
        Assert.assertTrue("Counter for 'Txn' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TxnIntegrationTest.testFindTxn() {
        Txn obj = dod.getRandomTxn();
        Assert.assertNotNull("Data on demand for 'Txn' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Txn' failed to provide an identifier", id);
        obj = Txn.findTxn(id);
        Assert.assertNotNull("Find method for 'Txn' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Txn' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TxnIntegrationTest.testFindAllTxns() {
        Assert.assertNotNull("Data on demand for 'Txn' failed to initialize correctly", dod.getRandomTxn());
        long count = Txn.countTxns();
        Assert.assertTrue("Too expensive to perform a find all test for 'Txn', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Txn> result = Txn.findAllTxns();
        Assert.assertNotNull("Find all method for 'Txn' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Txn' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TxnIntegrationTest.testFindTxnEntries() {
        Assert.assertNotNull("Data on demand for 'Txn' failed to initialize correctly", dod.getRandomTxn());
        long count = Txn.countTxns();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Txn> result = Txn.findTxnEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Txn' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Txn' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TxnIntegrationTest.testFlush() {
        Txn obj = dod.getRandomTxn();
        Assert.assertNotNull("Data on demand for 'Txn' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Txn' failed to provide an identifier", id);
        obj = Txn.findTxn(id);
        Assert.assertNotNull("Find method for 'Txn' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTxn(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Txn' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TxnIntegrationTest.testMergeUpdate() {
        Txn obj = dod.getRandomTxn();
        Assert.assertNotNull("Data on demand for 'Txn' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Txn' failed to provide an identifier", id);
        obj = Txn.findTxn(id);
        boolean modified =  dod.modifyTxn(obj);
        Integer currentVersion = obj.getVersion();
        Txn merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Txn' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TxnIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Txn' failed to initialize correctly", dod.getRandomTxn());
        Txn obj = dod.getNewTransientTxn(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Txn' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Txn' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Txn' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TxnIntegrationTest.testRemove() {
        Txn obj = dod.getRandomTxn();
        Assert.assertNotNull("Data on demand for 'Txn' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Txn' failed to provide an identifier", id);
        obj = Txn.findTxn(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Txn' with identifier '" + id + "'", Txn.findTxn(id));
    }
    
}
