// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.repay.wallet.domain;

import com.repay.wallet.domain.TxnType;
import com.repay.wallet.domain.TxnTypeDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect TxnTypeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TxnTypeDataOnDemand: @Component;
    
    private Random TxnTypeDataOnDemand.rnd = new SecureRandom();
    
    private List<TxnType> TxnTypeDataOnDemand.data;
    
    public TxnType TxnTypeDataOnDemand.getNewTransientTxnType(int index) {
        TxnType obj = new TxnType();
        setTxnTypeId(obj, index);
        setTxnTypeName(obj, index);
        return obj;
    }
    
    public void TxnTypeDataOnDemand.setTxnTypeId(TxnType obj, int index) {
        int txnTypeId = index;
        obj.setTxnTypeId(txnTypeId);
    }
    
    public void TxnTypeDataOnDemand.setTxnTypeName(TxnType obj, int index) {
        String txnTypeName = "txnTypeName_" + index;
        obj.setTxnTypeName(txnTypeName);
    }
    
    public TxnType TxnTypeDataOnDemand.getSpecificTxnType(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        TxnType obj = data.get(index);
        Long id = obj.getId();
        return TxnType.findTxnType(id);
    }
    
    public TxnType TxnTypeDataOnDemand.getRandomTxnType() {
        init();
        TxnType obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return TxnType.findTxnType(id);
    }
    
    public boolean TxnTypeDataOnDemand.modifyTxnType(TxnType obj) {
        return false;
    }
    
    public void TxnTypeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = TxnType.findTxnTypeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'TxnType' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<TxnType>();
        for (int i = 0; i < 10; i++) {
            TxnType obj = getNewTransientTxnType(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
