// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.repay.wallet.domain;

import com.repay.wallet.domain.TxnType;
import com.repay.wallet.domain.TxnTypeDataOnDemand;
import com.repay.wallet.domain.TxnTypeIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TxnTypeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TxnTypeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TxnTypeIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TxnTypeIntegrationTest: @Transactional;
    
    @Autowired
    TxnTypeDataOnDemand TxnTypeIntegrationTest.dod;
    
    @Test
    public void TxnTypeIntegrationTest.testCountTxnTypes() {
        Assert.assertNotNull("Data on demand for 'TxnType' failed to initialize correctly", dod.getRandomTxnType());
        long count = TxnType.countTxnTypes();
        Assert.assertTrue("Counter for 'TxnType' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TxnTypeIntegrationTest.testFindTxnType() {
        TxnType obj = dod.getRandomTxnType();
        Assert.assertNotNull("Data on demand for 'TxnType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TxnType' failed to provide an identifier", id);
        obj = TxnType.findTxnType(id);
        Assert.assertNotNull("Find method for 'TxnType' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'TxnType' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TxnTypeIntegrationTest.testFindAllTxnTypes() {
        Assert.assertNotNull("Data on demand for 'TxnType' failed to initialize correctly", dod.getRandomTxnType());
        long count = TxnType.countTxnTypes();
        Assert.assertTrue("Too expensive to perform a find all test for 'TxnType', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<TxnType> result = TxnType.findAllTxnTypes();
        Assert.assertNotNull("Find all method for 'TxnType' illegally returned null", result);
        Assert.assertTrue("Find all method for 'TxnType' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TxnTypeIntegrationTest.testFindTxnTypeEntries() {
        Assert.assertNotNull("Data on demand for 'TxnType' failed to initialize correctly", dod.getRandomTxnType());
        long count = TxnType.countTxnTypes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<TxnType> result = TxnType.findTxnTypeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'TxnType' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'TxnType' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TxnTypeIntegrationTest.testFlush() {
        TxnType obj = dod.getRandomTxnType();
        Assert.assertNotNull("Data on demand for 'TxnType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TxnType' failed to provide an identifier", id);
        obj = TxnType.findTxnType(id);
        Assert.assertNotNull("Find method for 'TxnType' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTxnType(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'TxnType' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TxnTypeIntegrationTest.testMergeUpdate() {
        TxnType obj = dod.getRandomTxnType();
        Assert.assertNotNull("Data on demand for 'TxnType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TxnType' failed to provide an identifier", id);
        obj = TxnType.findTxnType(id);
        boolean modified =  dod.modifyTxnType(obj);
        Integer currentVersion = obj.getVersion();
        TxnType merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'TxnType' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TxnTypeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'TxnType' failed to initialize correctly", dod.getRandomTxnType());
        TxnType obj = dod.getNewTransientTxnType(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'TxnType' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'TxnType' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'TxnType' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TxnTypeIntegrationTest.testRemove() {
        TxnType obj = dod.getRandomTxnType();
        Assert.assertNotNull("Data on demand for 'TxnType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TxnType' failed to provide an identifier", id);
        obj = TxnType.findTxnType(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'TxnType' with identifier '" + id + "'", TxnType.findTxnType(id));
    }
    
}
