// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.repay.wallet.domain;

import com.repay.wallet.domain.UserDtls;
import com.repay.wallet.domain.UserDtlsDataOnDemand;
import com.repay.wallet.domain.UserDtlsIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect UserDtlsIntegrationTest_Roo_IntegrationTest {
    
    declare @type: UserDtlsIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: UserDtlsIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: UserDtlsIntegrationTest: @Transactional;
    
    @Autowired
    UserDtlsDataOnDemand UserDtlsIntegrationTest.dod;
    
    @Test
    public void UserDtlsIntegrationTest.testCountUserDtlses() {
        Assert.assertNotNull("Data on demand for 'UserDtls' failed to initialize correctly", dod.getRandomUserDtls());
        long count = UserDtls.countUserDtlses();
        Assert.assertTrue("Counter for 'UserDtls' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void UserDtlsIntegrationTest.testFindUserDtls() {
        UserDtls obj = dod.getRandomUserDtls();
        Assert.assertNotNull("Data on demand for 'UserDtls' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserDtls' failed to provide an identifier", id);
        obj = UserDtls.findUserDtls(id);
        Assert.assertNotNull("Find method for 'UserDtls' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'UserDtls' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void UserDtlsIntegrationTest.testFindAllUserDtlses() {
        Assert.assertNotNull("Data on demand for 'UserDtls' failed to initialize correctly", dod.getRandomUserDtls());
        long count = UserDtls.countUserDtlses();
        Assert.assertTrue("Too expensive to perform a find all test for 'UserDtls', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<UserDtls> result = UserDtls.findAllUserDtlses();
        Assert.assertNotNull("Find all method for 'UserDtls' illegally returned null", result);
        Assert.assertTrue("Find all method for 'UserDtls' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void UserDtlsIntegrationTest.testFindUserDtlsEntries() {
        Assert.assertNotNull("Data on demand for 'UserDtls' failed to initialize correctly", dod.getRandomUserDtls());
        long count = UserDtls.countUserDtlses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<UserDtls> result = UserDtls.findUserDtlsEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'UserDtls' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'UserDtls' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void UserDtlsIntegrationTest.testFlush() {
        UserDtls obj = dod.getRandomUserDtls();
        Assert.assertNotNull("Data on demand for 'UserDtls' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserDtls' failed to provide an identifier", id);
        obj = UserDtls.findUserDtls(id);
        Assert.assertNotNull("Find method for 'UserDtls' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyUserDtls(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'UserDtls' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UserDtlsIntegrationTest.testMergeUpdate() {
        UserDtls obj = dod.getRandomUserDtls();
        Assert.assertNotNull("Data on demand for 'UserDtls' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserDtls' failed to provide an identifier", id);
        obj = UserDtls.findUserDtls(id);
        boolean modified =  dod.modifyUserDtls(obj);
        Integer currentVersion = obj.getVersion();
        UserDtls merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'UserDtls' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UserDtlsIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'UserDtls' failed to initialize correctly", dod.getRandomUserDtls());
        UserDtls obj = dod.getNewTransientUserDtls(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'UserDtls' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'UserDtls' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'UserDtls' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void UserDtlsIntegrationTest.testRemove() {
        UserDtls obj = dod.getRandomUserDtls();
        Assert.assertNotNull("Data on demand for 'UserDtls' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserDtls' failed to provide an identifier", id);
        obj = UserDtls.findUserDtls(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'UserDtls' with identifier '" + id + "'", UserDtls.findUserDtls(id));
    }
    
}
