// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.repay.wallet.domain;

import com.repay.wallet.domain.UserDtls;
import com.repay.wallet.domain.UserDtlsDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect UserDtlsDataOnDemand_Roo_DataOnDemand {
    
    declare @type: UserDtlsDataOnDemand: @Component;
    
    private Random UserDtlsDataOnDemand.rnd = new SecureRandom();
    
    private List<UserDtls> UserDtlsDataOnDemand.data;
    
    public UserDtls UserDtlsDataOnDemand.getNewTransientUserDtls(int index) {
        UserDtls obj = new UserDtls();
        setUserId(obj, index);
        setUserName(obj, index);
        return obj;
    }
    
    public void UserDtlsDataOnDemand.setUserId(UserDtls obj, int index) {
        int userId = index;
        obj.setUserId(userId);
    }
    
    public void UserDtlsDataOnDemand.setUserName(UserDtls obj, int index) {
        String userName = "userName_" + index;
        obj.setUserName(userName);
    }
    
    public UserDtls UserDtlsDataOnDemand.getSpecificUserDtls(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        UserDtls obj = data.get(index);
        Long id = obj.getId();
        return UserDtls.findUserDtls(id);
    }
    
    public UserDtls UserDtlsDataOnDemand.getRandomUserDtls() {
        init();
        UserDtls obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return UserDtls.findUserDtls(id);
    }
    
    public boolean UserDtlsDataOnDemand.modifyUserDtls(UserDtls obj) {
        return false;
    }
    
    public void UserDtlsDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = UserDtls.findUserDtlsEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'UserDtls' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<UserDtls>();
        for (int i = 0; i < 10; i++) {
            UserDtls obj = getNewTransientUserDtls(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
