// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.repay.wallet.domain;

import com.repay.wallet.domain.UserDtlsDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect UserDtlsDataOnDemand_Roo_Configurable {
    
    declare @type: UserDtlsDataOnDemand: @Configurable;
    
}
