// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.repay.wallet.domain;

import com.repay.wallet.domain.WalletType;
import com.repay.wallet.domain.WalletTypeDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect WalletTypeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: WalletTypeDataOnDemand: @Component;
    
    private Random WalletTypeDataOnDemand.rnd = new SecureRandom();
    
    private List<WalletType> WalletTypeDataOnDemand.data;
    
    public WalletType WalletTypeDataOnDemand.getNewTransientWalletType(int index) {
        WalletType obj = new WalletType();
        setWalletTypeDescription(obj, index);
        setWalletTypeId(obj, index);
        setWalletTypeName(obj, index);
        return obj;
    }
    
    public void WalletTypeDataOnDemand.setWalletTypeDescription(WalletType obj, int index) {
        String walletTypeDescription = "walletTypeDescription_" + index;
        obj.setWalletTypeDescription(walletTypeDescription);
    }
    
    public void WalletTypeDataOnDemand.setWalletTypeId(WalletType obj, int index) {
        int walletTypeId = index;
        obj.setWalletTypeId(walletTypeId);
    }
    
    public void WalletTypeDataOnDemand.setWalletTypeName(WalletType obj, int index) {
        String walletTypeName = "walletTypeName_" + index;
        obj.setWalletTypeName(walletTypeName);
    }
    
    public WalletType WalletTypeDataOnDemand.getSpecificWalletType(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        WalletType obj = data.get(index);
        Long id = obj.getId();
        return WalletType.findWalletType(id);
    }
    
    public WalletType WalletTypeDataOnDemand.getRandomWalletType() {
        init();
        WalletType obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return WalletType.findWalletType(id);
    }
    
    public boolean WalletTypeDataOnDemand.modifyWalletType(WalletType obj) {
        return false;
    }
    
    public void WalletTypeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = WalletType.findWalletTypeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'WalletType' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<WalletType>();
        for (int i = 0; i < 10; i++) {
            WalletType obj = getNewTransientWalletType(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
