// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.repay.wallet.domain;

import com.repay.wallet.domain.UserDtlsDataOnDemand;
import com.repay.wallet.domain.Wallet;
import com.repay.wallet.domain.WalletDataOnDemand;
import com.repay.wallet.domain.WalletTypeDataOnDemand;
import java.math.BigDecimal;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect WalletDataOnDemand_Roo_DataOnDemand {
    
    declare @type: WalletDataOnDemand: @Component;
    
    private Random WalletDataOnDemand.rnd = new SecureRandom();
    
    private List<Wallet> WalletDataOnDemand.data;
    
    @Autowired
    UserDtlsDataOnDemand WalletDataOnDemand.userDtlsDataOnDemand;
    
    @Autowired
    WalletTypeDataOnDemand WalletDataOnDemand.walletTypeDataOnDemand;
    
    public Wallet WalletDataOnDemand.getNewTransientWallet(int index) {
        Wallet obj = new Wallet();
        setBalance(obj, index);
        setCreatedBy(obj, index);
        setCreatedOn(obj, index);
        setCurrency(obj, index);
        setIsActive(obj, index);
        setModifiedBy(obj, index);
        setModifiedOn(obj, index);
        setWalletId(obj, index);
        return obj;
    }
    
    public void WalletDataOnDemand.setBalance(Wallet obj, int index) {
        BigDecimal balance = BigDecimal.valueOf(index);
        obj.setBalance(balance);
    }
    
    public void WalletDataOnDemand.setCreatedBy(Wallet obj, int index) {
        String createdBy = "createdBy_" + index;
        obj.setCreatedBy(createdBy);
    }
    
    public void WalletDataOnDemand.setCreatedOn(Wallet obj, int index) {
        Date createdOn = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreatedOn(createdOn);
    }
    
    public void WalletDataOnDemand.setCurrency(Wallet obj, int index) {
        String currency = "currency_" + index;
        obj.setCurrency(currency);
    }
    
    public void WalletDataOnDemand.setIsActive(Wallet obj, int index) {
        Boolean isActive = Boolean.TRUE;
        obj.setIsActive(isActive);
    }
    
    public void WalletDataOnDemand.setModifiedBy(Wallet obj, int index) {
        String modifiedBy = "modifiedBy_" + index;
        obj.setModifiedBy(modifiedBy);
    }
    
    public void WalletDataOnDemand.setModifiedOn(Wallet obj, int index) {
        Date modifiedOn = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setModifiedOn(modifiedOn);
    }
    
    public void WalletDataOnDemand.setWalletId(Wallet obj, int index) {
        int walletId = index;
        obj.setWalletId(walletId);
    }
    
    public Wallet WalletDataOnDemand.getSpecificWallet(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Wallet obj = data.get(index);
        Long id = obj.getId();
        return Wallet.findWallet(id);
    }
    
    public Wallet WalletDataOnDemand.getRandomWallet() {
        init();
        Wallet obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Wallet.findWallet(id);
    }
    
    public boolean WalletDataOnDemand.modifyWallet(Wallet obj) {
        return false;
    }
    
    public void WalletDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Wallet.findWalletEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Wallet' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Wallet>();
        for (int i = 0; i < 10; i++) {
            Wallet obj = getNewTransientWallet(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
