// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.repay.wallet.domain;

import com.repay.wallet.domain.Wallet;
import com.repay.wallet.domain.WalletDataOnDemand;
import com.repay.wallet.domain.WalletIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect WalletIntegrationTest_Roo_IntegrationTest {
    
    declare @type: WalletIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: WalletIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: WalletIntegrationTest: @Transactional;
    
    @Autowired
    WalletDataOnDemand WalletIntegrationTest.dod;
    
    @Test
    public void WalletIntegrationTest.testCountWallets() {
        Assert.assertNotNull("Data on demand for 'Wallet' failed to initialize correctly", dod.getRandomWallet());
        long count = Wallet.countWallets();
        Assert.assertTrue("Counter for 'Wallet' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void WalletIntegrationTest.testFindWallet() {
        Wallet obj = dod.getRandomWallet();
        Assert.assertNotNull("Data on demand for 'Wallet' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Wallet' failed to provide an identifier", id);
        obj = Wallet.findWallet(id);
        Assert.assertNotNull("Find method for 'Wallet' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Wallet' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void WalletIntegrationTest.testFindAllWallets() {
        Assert.assertNotNull("Data on demand for 'Wallet' failed to initialize correctly", dod.getRandomWallet());
        long count = Wallet.countWallets();
        Assert.assertTrue("Too expensive to perform a find all test for 'Wallet', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Wallet> result = Wallet.findAllWallets();
        Assert.assertNotNull("Find all method for 'Wallet' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Wallet' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void WalletIntegrationTest.testFindWalletEntries() {
        Assert.assertNotNull("Data on demand for 'Wallet' failed to initialize correctly", dod.getRandomWallet());
        long count = Wallet.countWallets();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Wallet> result = Wallet.findWalletEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Wallet' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Wallet' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void WalletIntegrationTest.testFlush() {
        Wallet obj = dod.getRandomWallet();
        Assert.assertNotNull("Data on demand for 'Wallet' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Wallet' failed to provide an identifier", id);
        obj = Wallet.findWallet(id);
        Assert.assertNotNull("Find method for 'Wallet' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyWallet(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Wallet' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void WalletIntegrationTest.testMergeUpdate() {
        Wallet obj = dod.getRandomWallet();
        Assert.assertNotNull("Data on demand for 'Wallet' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Wallet' failed to provide an identifier", id);
        obj = Wallet.findWallet(id);
        boolean modified =  dod.modifyWallet(obj);
        Integer currentVersion = obj.getVersion();
        Wallet merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Wallet' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void WalletIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Wallet' failed to initialize correctly", dod.getRandomWallet());
        Wallet obj = dod.getNewTransientWallet(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Wallet' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Wallet' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Wallet' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void WalletIntegrationTest.testRemove() {
        Wallet obj = dod.getRandomWallet();
        Assert.assertNotNull("Data on demand for 'Wallet' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Wallet' failed to provide an identifier", id);
        obj = Wallet.findWallet(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Wallet' with identifier '" + id + "'", Wallet.findWallet(id));
    }
    
}
